### PR TITLE
Fix the new style issues.

### PR DESCRIPTION
**Pull request by CarlFK**

### CODE REVIEW

**Comment by mithro** [comment]
```
0.31s$ make check
pycodestyle hdmi2usb --ignore=E402
hdmi2usb/modeswitch/cli.py:296:50: W504 line break after binary operator
hdmi2usb/modeswitch/cli.py:297:51: W504 line break after binary operator
hdmi2usb/modeswitch/cli.py:298:51: W504 line break after binary operator
hdmi2usb/modeswitch/cli.py:299:55: W504 line break after binary operator
hdmi2usb/modeswitch/cli.py:300:59: W504 line break after binary operator
hdmi2usb/modeswitch/cli.py:301:59: W504 line break after binary operator
hdmi2usb/modeswitch/cli.py:370:32: W504 line break after binary operator
hdmi2usb/modeswitch/cli.py:371:32: W504 line break after binary operator
hdmi2usb/modeswitch/cli.py:372:39: W504 line break after binary operator
make: *** [check] Error 1
The command "make check" exited with 2.
```

**Comment by CarlFK** [comment]
I can't figure our how to fix it.

```
296         if not args.mode and (
297             args.load_gateware \
298             or args.flash_gateware
299             or args.reset_gateware
300             or args.flash_softcpu_bios
301             or args.flash_softcpu_firmware
302             or args.clear_softcpu_firmware
303             or args.flash_image
304         ):

W504 line break after binary operator
moved or to next line:
W503 line break before binary operator
add a \
E502 the backslash is redundant between brackets
all on the same line:
 E501 line too long (185 > 79 characters)
```

**Comment by mithro** [comment]
I'm pretty sure it is asking for the following;
```
296         if not args.mode and (
297             args.load_gateware or
298             args.flash_gateware or
299             args.reset_gateware or
300             args.flash_softcpu_bios or
301             args.flash_softcpu_firmware or
302             args.clear_softcpu_firmware or
303             args.flash_image
304         ):
```

**Comment by CarlFK** [comment]
Nope.
```
296         if not args.mode and (
297             args.load_gateware or
298             args.flash_gateware or
299             args.reset_gateware or
300             args.flash_softcpu_bios or
301             args.flash_softcpu_firmware or
302             args.clear_softcpu_firmware or
303             args.flash_image
304         ):


pycodestyle hdmi2usb --ignore=E402
hdmi2usb/modeswitch/cli.py:297:13: W504 line break after binary operator
hdmi2usb/modeswitch/cli.py:298:13: W504 line break after binary operator
hdmi2usb/modeswitch/cli.py:299:13: W504 line break after binary operator
hdmi2usb/modeswitch/cli.py:300:13: W504 line break after binary operator
hdmi2usb/modeswitch/cli.py:301:13: W504 line break after binary operator
hdmi2usb/modeswitch/cli.py:302:13: W504 line break after binary operator
hdmi2usb/modeswitch/cli.py:372:17: W504 line break after binary operator
hdmi2usb/modeswitch/cli.py:373:17: W504 line break after binary operator
hdmi2usb/modeswitch/cli.py:374:17: W504 line break after binary operator
```

**Pull request closed without merging**
